### ISSUE TITLE
Turn-Based vs. Real-Time Modes

### ISSUE THREAD

**Issue by capnmikey** [v4nz666/RoguePy#12]
Determine where and how to handle these two fundamentally different styles of rogue-likes.

**Comment by v4nz666** [comment]
See #17. I think, given the current state of things, with tickHandlers, and inputHandlers, this would be trivial to just implement, in either mode. it's just a matter or whether you register your World.tick (or equivalent) method as a tick handler, or call it yourself, explicitly, at the end of a player turn (say, after the player moves/picks up an item).

**Comment by v4nz666** [comment]
Nothing to really do here. Closing.
