### ISSUE TITLE
Input overhaul

### ISSUE THREAD

**Issue by v4nz666** [v4nz666/RoguePy#15]
Things aren't right.

---

thoughts:
- setBlocking should live in the state manager.

**Comment by capnmikey** [comment]
Just wanted to note that blocking input should only be simulated, in the sense that program execution doesn't actually halt. This will allow fancy things like animation / event handling "in the background", while waiting for a keypress, without requiring multi-threading.

**Comment by v4nz666** [comment]
This will do, in terms of general functionality. Finer grained tickets to come.
